### ISSUE TITLE
windows下运行提示 已阻止应用程序python访问图形硬件

### ISSUE THREAD

**Issue by AlexYoung757** [MakDon/cnn-text-classification-tf-Chinese-py3#3]
错误提示如下：
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.76GiB
2017-07-06 20:18:27.796319: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:908] DMA: 0
2017-07-06 20:18:27.796804: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:918] 0:   Y
2017-07-06 20:18:27.799193: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:
00.0)
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.76GiB
2017-07-06 20:18:27.796319: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:908] DMA: 0
2017-07-06 20:18:27.796804: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:918] 0:   Y
2017-07-06 20:18:27.799193: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runti
me\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:
00.0)

2017-07-06 20:06:44.565761: E :\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\c
uda\cuda_driver.cc:1037] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED
2017-07-06 20:06:44.566149: E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\c
uda\cuda_timer.cc:54] Internal: error destroying CUDA event in context 000000B1BFD3AFA0: CUDA_ERROR_LAUNCH_FAILED
2017-07-06 20:06:44.566903: E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\c
uda\cuda_timer.cc:59] Internal: error destroying CUDA event in context 000000B1BFD3AFA0: CUDA_ERROR_LAUNCH_FAILED
2017-07-06 20:06:44.569491: F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\c
uda\cuda_dnn.cc:2478] failed to enqueue convolution on stream: CUDNN_STATUS_EXECUTION_FAILED

配置
显卡 GTX 960M 4G
操作系统 windows 8.1 professional
anaconda python 3.5.3
cuda 8.0 
cudnn v5.1

**Comment by MakDon** [comment]
我不太确定问题所在，以下是我的猜测：
你是否没有设置过TDR，然后再第一次跑的时候黑屏了，然后第二次再跑的时候提示“CUDNN_STATUS_EXECUTION_FAILED”
如果是，请调高TDR，具体操作可以google。
你之前是否有正常启动过tf的其它应用？
如果没有，请检查：
是否cudnn版本问题（此处用的是5.1）
是否python的权限不够（以管理员运行）

**Comment by AlexYoung757** [comment]
@MakDon  抱歉最近很忙，才看到您的回复。
根据您在readme里的提示一开始以及设置好TDR . 其他tf的应用正常，跑过minist数据。
相关环境如下
OS: windows 8.1
IDE: Anaconda 4.2
cuda：cuda 8.0
cudnn：cudnn 5.1

**Comment by MakDon** [comment]
那我不能确定问题了，经验有限。
google了一下有说法是驱动版本的问题，
还是只能请你自行解决了

**Comment by AlexYoung757** [comment]
还是非常感谢~~ 有说是cuda需要visual studio支持，驱动指的是nvidia驱动吗
